### ISSUE TITLE
RPM support

### ISSUE THREAD

**Issue by sammcj** [Al2Klimov/check_systemd_needrestart#13]
Looks like it's trying to find and use a Debian tool on a RHEL based distro (CentOS):

```
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

./check_systemd_needrestart.linux-amd64 | cat

'dpkg-query' '-W' '-f' 'Package=${Package}
Architecture=${Architecture}
Status=${Status}
Depends=${Depends}
Pre-Depends=${Pre-Depends}
Provides=${Provides}
Replaces=${Replaces}
Conffiles>
${Conffiles}
' '*': exec: "dpkg-query": executable file not found in $PATH
```

**Comment by Al2Klimov** [comment]
Hello @sammcj and thank you for reporting!

Unfortunately this plugin supports only Debian at the moment – feel free to create a PR for CentOS.

[showPackages()](https://github.com/Al2Klimov/check_systemd_needrestart/blob/1653ae15d4582346e94aedcf15b459e54db9fefa/pkg.go#L5) just need to call a new function rpmShowPackages() which works like [dpkgShowPackages()](https://github.com/Al2Klimov/check_systemd_needrestart/blob/1653ae15d4582346e94aedcf15b459e54db9fefa/dpkg.go#L23).

Best,
AK

**Comment by sammcj** [comment]
Thanks for responding @Al2Klimov, I haven't touched go before (more of a systems / platform engineer so most of my coding is automation with puppet / ruby), if I get a chance I'll take a look, but thanks again for responding regardless.

**Comment by Al2Klimov** [comment]
@sammcj Even if you couldn't do that, there's still e.g. my employer who also sells custom development:

sales@netways.de
